/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
//     public String getGreeting() {
//         return "Hello World!";
    // }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        ScientificCalculator calc = new ScientificCalculator();
        calc.add(1, 1);
        System.out.println(calc.getResult());
        calc.subtract(4, 2);
        System.out.println(calc.getResult());
        calc.multiply(5, 5);
        System.out.println(calc.getResult());
        calc.divide(10, 2);
        System.out.println(calc.getResult());
        double result = calc.cubeOf(4.0);
        System.out.println("cubeOf =" + result);
        int result = calc.modulo(5, 2);
        System.out.println("modulo = " + result);
    }
}

